FROM docker.io/ruby:2.7-slim
RUN apt-get update && apt-get install -y --no-install-recommends build-essential
WORKDIR /site
COPY Gemfile Gemfile.lock .
RUN bundle install
EXPOSE 4000
CMD bundle exec jekyll serve --incremental
